In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_column',None)
pd.set_option('display.width',None)

In [12]:
events=pd.read_csv('events.csv')
order_items=pd.read_csv('order_items.csv')
orders=pd.read_csv('orders.csv')
products=pd.read_csv('products.csv')
reviews=pd.read_csv('reviews.csv')
users=pd.read_csv('users.csv')

In [15]:
users.head(10)

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29
5,U000006,Michael Santiago,lynchgeorge@example.net,Male,East Steven,2024-04-21
6,U000007,Sara Watts,gabriellecameron@example.org,Male,Port Antonio,2024-07-03
7,U000008,Joseph Clark,jason76@example.net,Male,Thomasberg,2024-08-03
8,U000009,Anna Baker,zhurst@example.com,Other,East William,2024-06-17
9,U000010,Brandon Rodriguez,laurahenderson@example.org,Male,Jamesmouth,2024-03-03

In [17]:
users.info()
users.shape

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  str
 1   name         10000 non-null  str
 2   email        10000 non-null  str
 3   gender       10000 non-null  str
 4   city         10000 non-null  str
 5   signup_date  10000 non-null  str
dtypes: str(6)
memory usage: 468.9 KB

(10000, 6)

In [18]:
users['signup_date']=pd.to_datetime(users['signup_date'], errors='coerce')
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  str
 1   name         10000 non-null  str
 2   email        10000 non-null  str
 3   gender       10000 non-null  str
 4   city         10000 non-null  str
 5   signup_date  10000 non-null  datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 468.9 KB

In [24]:
reviews.head(10)

,review_id,order_id,product_id,user_id,rating,review_text,review_date
0,R00000528,O00000237,P001326,U001094,2,Color was different from images.,2025-10-14T12:03:56.749446
1,R00005792,O00002627,P000329,U001858,4,Highly recommend this brand.,2024-10-09T08:04:50.171793
2,R00036604,O00016798,P001160,U008109,4,Highly recommend this brand.,2024-06-03T05:11:16.787214
3,R00040163,O00018414,P001427,U006835,5,Highly recommend this brand.,2024-02-12T06:41:50.215810
4,R00031127,O00014300,P001639,U007148,3,Item arrived damaged.,2025-01-20T05:32:09.398860
5,R00012121,O00005571,P000545,U008471,2,Item arrived damaged.,2025-03-23T06:43:41.296484
6,R00000603,O00000268,P001726,U005394,4,"Not as expected, quality is poor.",2025-01-01T11:49:13.243196
7,R00010126,O00004654,P001747,U009810,2,"Excellent product, will buy again.",2025-09-07T13:15:38.158573
8,R00033877,O00015558,P000255,U004269,4,Decent product for the price.,2024-09-09T21:51:41.344570
9,R00019035,O00008786,P001146,U003737,4,Item arrived damaged.,2025-03-13T01:50:37.077642

In [20]:
reviews.info()
reviews.shape

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    15000 non-null  str
 1   order_id     15000 non-null  str
 2   product_id   15000 non-null  str
 3   user_id      15000 non-null  str
 4   rating       15000 non-null  int64
 5   review_text  15000 non-null  str
 6   review_date  15000 non-null  str
dtypes: int64(1), str(6)
memory usage: 820.4 KB

(15000, 7)

In [25]:
reviews['review_date']=pd.to_datetime(reviews['review_date'],errors='coerce')
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    15000 non-null  str
 1   order_id     15000 non-null  str
 2   product_id   15000 non-null  str
 3   user_id      15000 non-null  str
 4   rating       15000 non-null  int64
 5   review_text  15000 non-null  str
 6   review_date  15000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 820.4 KB

In [26]:
products.head(10)

  product_id     product_name        category    brand   price  rating
0    P000001         Astra Be        Clothing    Astra  157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech   21.46    3.87
2    P000003     Acme Discuss          Sports     Acme  265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus  541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra  198.00    3.97
5    P000006     NeoTech When            Toys  NeoTech   18.61    3.20
6    P000007    Zenith School            Toys   Zenith   81.17    2.61
7    P000008   Everest Friend        Clothing  Everest   33.86    2.93
8    P000009        Harbor Go  Home & Kitchen   Harbor  253.18    4.44
9    P000010      Orion Ahead          Sports    Orion  235.11    3.47

In [27]:
products.info()
products.shape

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2000 non-null   str
 1   product_name  2000 non-null   str
 2   category      2000 non-null   str
 3   brand         2000 non-null   str
 4   price         2000 non-null   float64
 5   rating        2000 non-null   float64
dtypes: float64(2), str(4)
memory usage: 93.9 KB

(2000, 6)

In [28]:
orders.head(10)

    order_id  user_id                  order_date order_status  total_amount
0  O00000001  U009310  2025-09-09T14:52:37.292731   processing        689.66
1  O00000002  U003247  2025-04-15T01:18:27.193404    completed       1666.85
2  O00000003  U007252  2025-04-27T15:37:48.008624   processing        665.06
3  O00000004  U008986  2025-10-04T20:35:22.204857    cancelled        689.50
4  O00000005  U008537  2024-11-13T08:15:18.498252    cancelled        860.50
5  O00000006  U003449  2024-10-13T09:02:26.848944    completed       2258.34
6  O00000007  U006985  2024-05-01T04:44:56.418188     returned        769.71
7  O00000008  U007661  2024-03-03T23:33:22.844913    completed         15.21
8  O00000009  U000610  2025-10-29T07:00:11.203638    cancelled        229.02
9  O00000010  U003175  2024-08-13T07:04:24.298799     returned        107.63

In [29]:
orders.info()
orders.shape

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  str
 1   user_id       20000 non-null  str
 2   order_date    20000 non-null  str
 3   order_status  20000 non-null  str
 4   total_amount  20000 non-null  float64
dtypes: float64(1), str(4)
memory usage: 781.4 KB

(20000, 5)

In [30]:
orders['order_date']=pd.to_datetime(orders['order_date'],errors='coerce')
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  str
 1   user_id       20000 non-null  str
 2   order_date    20000 non-null  datetime64[us]
 3   order_status  20000 non-null  str
 4   total_amount  20000 non-null  float64
dtypes: datetime64[us](1), float64(1), str(3)
memory usage: 781.4 KB

In [31]:
order_items.head(10)

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
0,I00000001,O00000001,P001758,U009310,2,8.07,16.14
1,I00000002,O00000001,P001119,U009310,1,74.08,74.08
2,I00000003,O00000001,P001794,U009310,1,576.97,576.97
3,I00000004,O00000001,P001038,U009310,1,22.47,22.47
4,I00000005,O00000002,P000859,U003247,1,422.22,422.22
5,I00000006,O00000002,P000803,U003247,1,953.03,953.03
6,I00000007,O00000002,P000324,U003247,1,60.11,60.11
7,I00000008,O00000002,P000454,U003247,1,231.49,231.49
8,I00000009,O00000003,P001344,U007252,1,103.47,103.47
9,I00000010,O00000003,P000919,U007252,1,33.99,33.99

In [32]:
order_items.info()
order_items.shape

<class 'pandas.DataFrame'>
RangeIndex: 43525 entries, 0 to 43524
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  43525 non-null  str
 1   order_id       43525 non-null  str
 2   product_id     43525 non-null  str
 3   user_id        43525 non-null  str
 4   quantity       43525 non-null  int64
 5   item_price     43525 non-null  float64
 6   item_total     43525 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 2.3 MB

(43525, 7)

In [33]:
events.head(10)

    event_id  user_id product_id event_type             event_timestamp
0  E00000001  U009798    P001393       cart  2025-07-08T14:28:55.893919
1  E00000002  U005881    P000669       view  2025-10-19T23:00:44.067982
2  E00000003  U006348    P001404       view  2025-05-09T07:02:42.256662
3  E00000004  U002664    P000400       cart  2025-07-19T22:47:07.019634
4  E00000005  U005776    P000392       view  2024-10-24T10:20:33.602165
5  E00000006  U002711    P001643       view  2024-12-20T11:02:39.321604
6  E00000007  U003726    P000370       view  2024-06-06T05:16:39.778558
7  E00000008  U002658    P001221       view  2025-03-31T05:39:53.288602
8  E00000009  U001433    P000240       view  2024-10-17T08:29:00.460950
9  E00000010  U000431    P000652       view  2024-10-27T10:56:00.683131

In [34]:
events.info()
events.shape

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         80000 non-null  str
 1   user_id          80000 non-null  str
 2   product_id       80000 non-null  str
 3   event_type       80000 non-null  str
 4   event_timestamp  80000 non-null  str
dtypes: str(5)
memory usage: 3.1 MB

(80000, 5)

In [38]:
events['event_timestamp']=pd.to_datetime(events['event_timestamp'],errors='coerce')
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         80000 non-null  str
 1   user_id          80000 non-null  str
 2   product_id       80000 non-null  str
 3   event_type       80000 non-null  str
 4   event_timestamp  80000 non-null  datetime64[us]
dtypes: datetime64[us](1), str(4)
memory usage: 3.1 MB

In [39]:
primary_keys = {
    'users': (users, 'user_id'),
    'orders': (orders, 'order_id'),
    'order_items': (order_items, 'order_item_id'),
    'products': (products, 'product_id'),
    'reviews': (reviews, 'review_id'),
    'events': (events, 'event_id')
}

for table_name, (df, key) in primary_keys.items():
    print(
        table_name,
        '| unique:', df[key].is_unique,
        '| missing:', df[key].isna().sum()
    )

users | unique: True | missing: 0
orders | unique: True | missing: 0
order_items | unique: True | missing: 0
products | unique: True | missing: 0
reviews | unique: True | missing: 0
events | unique: True | missing: 0

In [40]:
foreign_keys = [
    ('orders.user_id', orders['user_id'], users['user_id']),
    ('order_items.order_id', order_items['order_id'], orders['order_id']),
    ('order_items.product_id', order_items['product_id'], products['product_id']),
    ('order_items.user_id', order_items['user_id'], users['user_id']),
    ('reviews.order_id', reviews['order_id'], orders['order_id']),
    ('reviews.product_id', reviews['product_id'], products['product_id']),
    ('reviews.user_id', reviews['user_id'], users['user_id']),
    ('events.user_id', events['user_id'], users['user_id']),
    ('events.product_id', events['product_id'], products['product_id'])
]

for relationship, child_key, parent_key in foreign_keys:
    invalid_count = (~child_key.isin(parent_key)).sum()
    print(relationship, '| invalid values:', invalid_count)

orders.user_id | invalid values: 0
order_items.order_id | invalid values: 0
order_items.product_id | invalid values: 0
order_items.user_id | invalid values: 0
reviews.order_id | invalid values: 0
reviews.product_id | invalid values: 0
reviews.user_id | invalid values: 0
events.user_id | invalid values: 0
events.product_id | invalid values: 0

In [41]:
order_user_check = order_items.merge(
    orders[['order_id', 'user_id']],
    on='order_id',
    suffixes=('_item', '_order')
)

(order_user_check['user_id_item'] != order_user_check['user_id_order']).sum()

np.int64(0)

In [42]:
pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\KIIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.0.49)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\KIIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\KIIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 13.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("password")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/ecommerce"
)

In [55]:
tables = {
    "users": users,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "reviews": reviews,
    "events": events
}

for table_name, df in tables.items():
    df.to_sql(
        table_name,
        engine,
        if_exists="replace",
        index=False
    )
    print(f"{table_name} uploaded successfully!")

users uploaded successfully!
orders uploaded successfully!
order_items uploaded successfully!
products uploaded successfully!
reviews uploaded successfully!
events uploaded successfully!